const reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover:hover) and (pointer:fine)'),compact=matchMedia('(max-width:650px)');
const intro=document.querySelector('.intro'),canvas=document.querySelector('#atmosphere'),ctx=canvas.getContext('2d'),rig=document.querySelector('#badge-rig'),badge=document.querySelector('#badge');
let w=0,h=0,t=0,paused=reduced.matches,raf=0,last=0,angle=-7,velocity=0,target=-7,dragging=false,startX=0,startAngle=0,pointerX=0,pointerY=0;
const stars=Array.from({length:38},(_,i)=>({x:((i*271+33)%997)/997,y:((i*137+59)%773)/773,size:1.3+(i%4)*.65,phase:i*1.43}));
function fit(){const r=intro.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);paint()}
function paint(){ctx.clearRect(0,0,w,h);for(const s of stars){const x=(s.x*w+t*(3+s.size))%(w+30)-15+pointerX*8,y=s.y*h+Math.sin(t*.14+s.phase)*15+pointerY*5;ctx.save();ctx.translate(x,y);ctx.rotate(-.3);const g=ctx.createLinearGradient(-s.size*3,0,s.size*3,0);g.addColorStop(0,'#4368fd00');g.addColorStop(.4,'#6554d777');g.addColorStop(.65,'#b89aef99');g.addColorStop(1,'#ec6c6244');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(-s.size*3,-s.size);ctx.lineTo(s.size*1.5,-s.size*.7);ctx.lineTo(s.size*3,s.size);ctx.lineTo(-s.size,s.size*.6);ctx.closePath();ctx.fill();ctx.restore()}}
function frame(now){raf=0;const dt=Math.min((now-last)/1000||.016,.033);last=now;if(!paused)t+=dt;const desired=dragging?target:-7+(paused?0:Math.sin(t*.65)*1.25);if(reduced.matches){angle=desired;velocity=0}else{velocity+=(desired-angle)*45*dt;velocity*=Math.exp(-8*dt);angle+=velocity*dt;}rig.style.setProperty('--swing',angle.toFixed(3)+'deg');paint();paintSections();if(!document.hidden&&(!paused||dragging||Math.abs(angle-desired)>.01))raf=requestAnimationFrame(frame)}
function wake(){if(!raf&&!document.hidden){last=performance.now();raf=requestAnimationFrame(frame)}}
intro.addEventListener('pointermove',e=>{const r=intro.getBoundingClientRect();pointerX=(e.clientX-r.left)/r.width-.5;pointerY=(e.clientY-r.top)/r.height-.5;if(!reduced.matches){document.querySelector('.eyes').style.setProperty('--eye-x',pointerX*10+'px');document.querySelector('.eyes').style.setProperty('--eye-y',pointerY*9+'px')}});
intro.addEventListener('pointerleave',()=>{pointerX=pointerY=0;document.querySelector('.eyes').style.setProperty('--eye-x','0px');document.querySelector('.eyes').style.setProperty('--eye-y','0px')});
badge.addEventListener('pointerdown',e=>{if(e.target.closest('.qr-trigger'))return;dragging=true;startX=e.clientX;startAngle=angle;target=angle;badge.setPointerCapture(e.pointerId);wake()});badge.addEventListener('pointermove',e=>{if(dragging)target=Math.max(-23,Math.min(20,startAngle+(e.clientX-startX)*.12))});function release(){dragging=false;wake()}badge.addEventListener('pointerup',release);badge.addEventListener('pointercancel',release);badge.addEventListener('lostpointercapture',release);badge.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();velocity+=e.key==='ArrowLeft'?-40:40;wake()}});
const motion=document.querySelector('.motion');function label(){document.body.classList.toggle('motion-paused',paused);motion.textContent=paused?'播放动效':'暂停动效';motion.setAttribute('aria-pressed',String(paused));motion.title=motion.textContent}motion.onclick=()=>{paused=!paused;label();wake()};reduced.addEventListener('change',()=>{paused=reduced.matches;label();wake()});document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else wake()});new ResizeObserver(fit).observe(intro);label();wake();
const accordion=document.querySelector('.project-accordion'),panels=[...document.querySelectorAll('.project-panel')];
function activate(panel){accordion.classList.toggle('has-active',!!panel);panels.forEach(p=>{const on=p===panel;p.classList.toggle('active',on);p.querySelector('.expand-panel').setAttribute('aria-expanded',String(on));p.querySelector('.expand-panel').textContent=on?'收起封面 −':'展开封面 ＋'})}
panels.forEach(p=>{p.addEventListener('pointerenter',()=>{if((fine.matches&&!compact.matches))activate(p)});p.querySelector('a').addEventListener('focus',()=>{if((fine.matches&&!compact.matches)||p.querySelector('a').matches(':focus-visible'))activate(p)});p.querySelector('a').addEventListener('click',e=>{if(!(fine.matches&&!compact.matches)&&!p.classList.contains('active')){e.preventDefault();activate(p)}});p.querySelector('.expand-panel').onclick=()=>activate(p.classList.contains('active')?null:p)});accordion.addEventListener('pointerleave',()=>{if((fine.matches&&!compact.matches)&&!accordion.contains(document.activeElement))activate(null)});accordion.addEventListener('focusout',e=>{if(!accordion.contains(e.relatedTarget))activate(null)});accordion.addEventListener('keydown',e=>{if(e.key==='Escape')activate(null)});
let timer;
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',async()=>{const value=button.dataset.copy;let ok=false;try{await navigator.clipboard.writeText(value);ok=true}catch{const input=document.createElement('textarea');input.value=value;input.style.cssText='position:fixed;top:0;left:0;opacity:0';document.body.append(input);input.select();ok=document.execCommand('copy');input.remove();button.focus()}const toast=document.querySelector('.toast');toast.textContent=ok?'已复制'+button.dataset.label+'：'+value:'请手动复制：'+value;clearTimeout(timer);timer=setTimeout(()=>toast.textContent='',3000)}));
const qrDialog=document.querySelector('.qr-dialog');document.querySelector('.qr-trigger').addEventListener('click',()=>qrDialog.showModal());document.querySelector('.qr-close').onclick=()=>qrDialog.close();qrDialog.addEventListener('click',e=>{if(e.target===qrDialog){const r=qrDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)qrDialog.close()}});
const surfaces=[...document.querySelectorAll('.section-particles')].map((c,index)=>({canvas:c,ctx:c.getContext('2d'),section:c.parentElement,w:0,h:0,x:0,y:0,visible:true,stars:stars.slice(0,index===0?22:18)}));
function paintSections(){for(const v of surfaces){if(!v.visible)continue;const c=v.ctx;c.clearRect(0,0,v.w,v.h);for(const s of v.stars){const x=(s.x*v.w+t*(3+s.size))%(v.w+30)-15+v.x*8,y=s.y*v.h+Math.sin(t*.14+s.phase)*15+v.y*5;c.save();c.translate(x,y);c.rotate(-.3);const g=c.createLinearGradient(-s.size*3,0,s.size*3,0);g.addColorStop(0,'#4368fd00');g.addColorStop(.4,'#6554d777');g.addColorStop(.65,'#b89aef99');g.addColorStop(1,'#ec6c6244');c.fillStyle=g;c.beginPath();c.moveTo(-s.size*3,-s.size);c.lineTo(s.size*1.5,-s.size*.7);c.lineTo(s.size*3,s.size);c.lineTo(-s.size,s.size*.6);c.closePath();c.fill();c.restore()}}}
for(const v of surfaces){new ResizeObserver(()=>{const r=v.section.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);v.w=r.width;v.h=r.height;v.canvas.width=v.w*d;v.canvas.height=v.h*d;v.ctx.setTransform(d,0,0,d,0,0);paintSections()}).observe(v.section);new IntersectionObserver(([entry])=>{v.visible=entry.isIntersecting;if(v.visible)paintSections()}).observe(v.section);v.section.addEventListener('pointermove',e=>{if(paused||reduced.matches)return;const r=v.section.getBoundingClientRect();v.x=(e.clientX-r.left)/r.width-.5;v.y=(e.clientY-r.top)/r.height-.5});v.section.addEventListener('pointerleave',()=>{v.x=v.y=0})}
const contact=document.querySelector('.contact');contact.addEventListener('pointermove',e=>{if(paused||reduced.matches)return;const r=contact.getBoundingClientRect();contact.style.setProperty('--light-x',((e.clientX-r.left)/r.width-.5)*55+'px');contact.style.setProperty('--light-y',((e.clientY-r.top)/r.height-.5)*40+'px')});contact.addEventListener('pointerleave',()=>{contact.style.setProperty('--light-x','0px');contact.style.setProperty('--light-y','0px')});
// An upward wheel gesture over the personal introduction returns to the cover.
// It is scoped to the intro region so normal upward scrolling in later sections stays intact.
let returningHome=false,upWheel=0,upWheelAt=0;
const introRegion=document.querySelector('.intro');
function maybeReturnHome(event){
  if(returningHome||event.ctrlKey||event.deltaY>=0||!introRegion)return;
  const bounds=introRegion.getBoundingClientRect();
  const overIntro=bounds.top<innerHeight*.7&&bounds.bottom>innerHeight*.3;
  if(!overIntro)return;
  const now=performance.now();if(now-upWheelAt>300)upWheel=0;upWheelAt=now;
  const unit=event.deltaMode===1?16:event.deltaMode===2?innerHeight:1;
  upWheel+=Math.abs(event.deltaY)*unit;
  if(upWheel>=12){returningHome=true;location.href='index.html'}
}
window.addEventListener('wheel',maybeReturnHome,{passive:true,capture:true});
introRegion?.addEventListener('wheel',maybeReturnHome,{passive:true});
